services:
  db:
    image: postgres
    container_name: wcy-postgres
    restart: always
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
      POSTGRES_DB: ${POSTGRES_DB:-local}
    volumes:
      - pgdata:/var/lib/postgresql/dbdata

volumes:
  pgdata:
